### ISSUE TITLE
cmd line hangs and webui does not update port

### ISSUE THREAD

**Issue by 7gxycn08** [maah/ProtonVPN-win-app#2] opened 2023-09-25 14:33 UTC
cmd line hangs qbittorrent 4.5.5 gets stuck on shutting down when active torrents are running.

the webui method does not update port tried reconnecting multiple times and it still doesn't work.

**Comment by maah** [comment] 2023-09-25 15:15
>  qbittorrent 4.5.5 gets stuck [...] when active torrents are running

This is intended behavior, and can be changed in qBittorrent's settings: `Confirmation on exit when torrents are active`.

> the webui method does not update port

There's not much I can do without any details, but that sounds like a config issue on your end.
Did you enable it in qBittorrent's settings? It it set up correctly?
Check if you can access it through web browser.

**Comment by maah** [comment] 2023-09-25 16:21
>  Is there a way to retrieve the current open port number from a Protonvpn config file?  
Not that I know of.  

If it's accessible from a web browser, then it should work.  
Aside from trying with qBittorrent's localhost authentication bypass, I'm not sure what the issue would be.

**Comment by 7gxycn08** [comment] 2023-09-26 01:26
Can you tell me how to build the solution order I'm getting false positives when i use the released binary.

When I build the .sln It gives me a warning that protonvpn.service is not installed I think i need to build it with the installer.

**Comment by 7gxycn08** [comment] 2023-09-26 03:52
Using this string command fixes the the issue of Qbittorrent stuck in shutdown when updating the port.

`private void UpdatePortViaCommandLine(int port)
{
    string command = string.Format("FOR /L %x IN (1, 1, 10) DO taskkill /F /IM qbittorrent.exe & "
        + "tasklist | find /I \"qbittorrent.exe\" & "
        + "IF ERRORLEVEL 1 (start \"\" \"C:\\Program Files\\qBittorrent\\qbittorrent.exe\" --torrenting-port={0} & exit) "
        + "ELSE (timeout /T 2)"
        , port);`

**Comment by maah** [comment] 2023-09-26 09:39
Build instruction can be found in [BUILD.MD](https://github.com/maah/ProtonVPN-win-app/blob/master/BUILD.md).  
That code already runs via the command line option, cf. my first reply.  

Closing this as you seem to have fixed your settings + GitHub issues are not for general questions.

**Closed by maah** 2023-09-26 09:39 UTC

**Comment by 7gxycn08** [comment] 2023-09-26 09:47
Many steps are missing from [BUILD.MD](https://github.com/maah/ProtonVPN-win-app/blob/master/BUILD.md)

It's useless.
